version: '3.8'

services:
  backend:
    image: example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    container_name: backend

  frontend:
    image: example-frontend
    ports:
      - 5678:5000
    container_name: frontend

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: db
