version: '3.8'

services:
  backend:
    image: example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - REQUEST_ORIGIN=http://localhost:80
      - POSTGRES_HOST=db
    container_name: backend
    command: ["./server", "${REQUEST_ORIGIN}"]

  frontend:
    image: example-frontend
    ports:
      - 5678:5000
    container_name: frontend

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database:/var/lib/postgresql/data
    container_name: db

  nginx:
    image: nginx:stable-perl
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    container_name: proxy

volumes:
  database:
