FROM node:16.20.2-alpine3.18 as build-stage
WORKDIR /usr/app

COPY package* ./
RUN npm install

COPY . .
ENV REACT_APP_BACKEND_URL=http://localhost:8080
RUN npm run build ${REACT_APP_BACKEND_URL}

FROM node:16.20.2-alpine3.18
WORKDIR /usr/app

COPY --from=build-stage /usr/app/build /usr/app/build
EXPOSE 5000
RUN npm install -g serve && adduser -D appuser
USER appuser
CMD ["serve", "-s", "-l", "5000", "build"]
